### ISSUE TITLE
Docker Image configuration

### ISSUE THREAD

**Issue by jdev1022** [jdev1022/py-docker-aws-example#1]
Hello Everyone.
I have just completed this project, but as you can see I am installing the Python3 inside the Docker image manually.
But when I see the documents on AWS, it shows we can get using the pre-built images.

**Comment by webmaster0407** [comment]
When you jump into the documentation , you can see the following codebase, (It is sourced from my project)

```shell
FROM public.ecr.aws/lambda/python:3.8

COPY ./app.py .
COPY ./ffmpeg .
COPY ./requirements.txt  /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt --target . && \
    chmod -R 755 .

WORKDIR /var/task
ENV PATH="/var/task:${PATH}"

CMD [ "app.handler" ]
``` 

I think you can just pull the images using the first line of the above codeblock.
It maybe helpful for you.
